title: Anil Niraula # your name (or website title) here
logo: "/images/Anil (photo 2).jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  Have extensive hands-on experience w/ MS Office | PostgreSQL | R | R Markdown | GitHub | Git | doing data analytics, data prep & database management (ETL flow), developing R packages & interactive apps, econometric & actuarial modeling, machine learning and applied research.
  <br><br>
  Career interests in data science, analytics, and personal finance.
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
