title: Anil Niraula # your name (or website title) here
logo: "/images/Anil (photo 2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Have more than 6 years of experience in financial consulting, data analytics, data management, econometric modeling and applied research.
  <br><br>
 Key skills in: data management, data analytics, economic analysis, econometric modeling, research, project-management and consulting.
  <br><br>
   Career interests: quantitative and qualitative analysis, public policy research, survey analysis.
   <br><br>
  <a href="https://www.linkedin.com/in/anil-niraula-603a0825/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
