title: Anil Niraula # your name (or website title) here
logo: "/images/Anil (photo 2).jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist/Analyst with 8+ years of hands-on experience using Python | PyTorch | TensorFlow | R | Azure AI | SQL | SAS | Shell | Snowflake | Tableau | Git | Jira | MS Office for data science, machine learning & AI (traning, validation and deployment), analytics, applied research, data prep & database management (ETL flow), developing R packages & interactive apps.
  <br><br>
  Career interests in data science, ML, analytics, and personal finance.
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
