title: Anil Niraula # your name (or website title) here
logo: "/images/Anil (photo 2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Have extensive hands-on experience w/ MS Office & SQL & R econsistems in data analytics, data prep & management, developing packages & apps, econometric modeling and applied research.
  <br><br>
  Career interests in quantitative and qualitative analysis, public policy research, and investments
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
